namespace :ci do

  namespace :test do

    desc <<-EOS.gsub(/^ {6}/, '')
      A quick acceptance test, named because it has no pre-suites to run
      EOS
    task :quick do
      sh("beaker",
         "--hosts", ENV['CONFIG'] || ENV['HOSTS'] || "config/nodes/redhat-7-x86_64.yaml",
         "--tests", ENV['TESTS'] || "tests",
         '--log-level', 'verbose',
         "--keyfile", ENV['KEY'] || "#{ENV['HOME']}/.ssh/id_rsa")
    end

  end

end

task :default => 'ci:test:quick'
